import turtle 

subOut = turtle.Turtle()
subOut.speed(0)

def submarineOutline():

    subOut.penup()
    subOut.setpos(120,-100)
    subOut.fillcolor("#C9C9C9")
    subOut.begin_fill()
    subOut.pendown()
    subOut.pencolor("#C7C7C7")
    subOut.circle(80,180) #subCockpit
    subOut.forward(70)    #sublength = 50+30
    subOut.right(180)
    subOut.circle(20,-90)   #sublength = 50+30+20
    subOut.right(180)
    subOut.forward(50)
    subOut.right(180)
    subOut.circle(10,-90)
    subOut.right(180)
    subOut.forward(15)
    subOut.left(90)
    subOut.forward(20)
    subOut.left(90)
    subOut.forward(30)     #sublength = 50 + 30 + 20 + 20 + 10 + 15
    subOut.circle(15,90)
    subOut.forward(65)
    subOut.right(90)
    subOut.forward(85)      #sublength = 50 + 30 + 20 + 20 +10 + 15 + 85
    subOut.circle(20,90)
    subOut.right(90)
    subOut.forward(70)      #sublength = 50 + 30 + 20 + 20 + 10 + 15 + 85 + 10 + 70
    subOut.circle(50,90)
    subOut.right(90)
    subOut.circle(55,180)
    subOut.forward(150)
    subOut.right(90)
    subOut.circle(40,180)
    subOut.right(90)
    subOut.forward(115)
    subOut.end_fill()

    subOut.hideturtle()

subIn = turtle.Turtle()
subIn.speed(0)

def submarineInline():

    #SubHandleFront
    subIn.penup()
    subIn.setpos(120,-100)
    subIn.pendown()  
    subIn.pencolor("#474747")
    subIn.width(3)
    subIn.left(90)
    subIn.forward(40)
    subIn.penup()
    subIn.fillcolor("#313131")
    subIn.begin_fill()
    subIn.pensize(0)
    subIn.setpos(135,-60)
    subIn.pendown()
    subIn.left(90)
    subIn.forward(30)
    subIn.right(90)
    subIn.forward(10)
    subIn.right(90)
    subIn.forward(30)
    subIn.right(90)
    subIn.forward(10)
    subIn.end_fill()

    #alienChair1Stand
    subIn.penup()
    subIn.setpos(75,-100)
    subIn.pendown()
    subIn.right(180)
    subIn.width(3)
    subIn.forward(60)

    #alienChair1
    subIn.penup()
    subIn.setpos(75,-70)
    subIn.pendown()
    subIn.begin_fill()
    subIn.width(1)
    subIn.left(60)
    subIn.forward(20)
    subIn.right(90)
    subIn.forward(25)
    subIn.left(120)
    subIn.forward(15)
    subIn.right(90)
    subIn.forward(20)
    subIn.right(90)
    subIn.forward(5)
    subIn.right(90)
    subIn.forward(15)
    subIn.left(90)
    subIn.forward(20)
    subIn.right(90)
    subIn.forward(5)
    subIn.right(60)
    subIn.forward(5)
    subIn.left(30)
    subIn.forward(20)
    subIn.left(90)
    subIn.forward(10)
    subIn.end_fill()

    #subGearBox
    subIn.penup()
    subIn.setpos(50,-100)
    subIn.begin_fill()
    subIn.pendown()
    subIn.right(150)
    subIn.forward(25)
    subIn.right(90)
    subIn.forward(7)
    subIn.right(90)
    subIn.forward(25)
    subIn.right(90)
    subIn.forward(7)
    subIn.end_fill()
    subIn.penup()
    subIn.setpos(37,-93)
    subIn.pendown()
    subIn.pensize(3)
    subIn.right(180)
    subIn.forward(65)
    subIn.right(90)
    subIn.begin_fill()
    subIn.pensize(0)
    subIn.circle(4)
    subIn.end_fill()

    #alienChair2stand
    subIn.penup()
    subIn.setpos(18,-100)
    subIn.left(90)
    subIn.pendown()
    subIn.pensize(3)
    subIn.forward(20)
    subIn.left(90)
    subIn.forward(13)
    subIn.right(90)
    subIn.forward(50)

    #alienChair2
    subIn.penup()
    subIn.setpos(5, -60)
    subIn.pendown()
    subIn.begin_fill()
    subIn.width(1)
    subIn.left(60)
    subIn.forward(20)
    subIn.right(90)
    subIn.forward(25)
    subIn.left(120)
    subIn.forward(15)
    subIn.right(90)
    subIn.forward(20)
    subIn.right(90)
    subIn.forward(5)
    subIn.right(90)
    subIn.forward(15)
    subIn.left(90)
    subIn.forward(20)
    subIn.right(90)
    subIn.forward(5)
    subIn.right(60)
    subIn.forward(5)
    subIn.left(30)
    subIn.forward(20)
    subIn.left(90)
    subIn.forward(10)
    subIn.end_fill()

    #alien3Handle
    subIn.penup()
    subIn.setpos(-30,-95)
    subIn.pendown()
    subIn.right(150)
    subIn.width(3)
    subIn.forward(5)
    subIn.right(90)
    subIn.forward(70)
    subIn.circle(5,90)
    subIn.forward(10)

    #alienChair3Stand
    subIn.penup()
    subIn.setpos(-70, -100)
    subIn.left(90)
    subIn.pendown()
    subIn.right(180)
    subIn.width(3)
    subIn.forward(60)

    #alienChair3
    subIn.penup()
    subIn.setpos(-70, -70)
    subIn.pendown()
    subIn.begin_fill()
    subIn.width(1)
    subIn.left(60)
    subIn.forward(20)
    subIn.right(90)
    subIn.forward(25)
    subIn.left(120)
    subIn.forward(15)
    subIn.right(90)
    subIn.forward(20)
    subIn.right(90)
    subIn.forward(5)
    subIn.right(90)
    subIn.forward(15)
    subIn.left(90)
    subIn.forward(20)
    subIn.right(90)
    subIn.forward(5)
    subIn.right(60)
    subIn.forward(5)
    subIn.left(30)
    subIn.forward(20)
    subIn.left(90)
    subIn.forward(10)
    subIn.end_fill()

    #shaft1
    subIn.penup()
    subIn.setpos(-95,-75)
    subIn.pendown()
    subIn.right(150)
    subIn.width(3)
    subIn.forward(60)

    #shaft2
    subIn.penup()
    subIn.setpos(-95, -55)
    subIn.pendown()
    subIn.width(3)
    subIn.forward(60)

    #mainShaftback
    subIn.penup()
    subIn.setpos(-180, -40)
    subIn.pendown()
    subIn.width(8)
    subIn.forward(115)

    #mainShaftbackComponents
    subIn.penup()
    subIn.setpos(-185,-54)
    subIn.pendown()
    subIn.width(0)
    subIn.begin_fill()
    subIn.right(45)
    subIn.forward(10)
    subIn.right(45)
    subIn.forward(15)
    subIn.right(45)
    subIn.forward(10)
    subIn.right(45)
    subIn.end_fill()
    subIn.penup()
    subIn.setpos(-280,-35)
    subIn.begin_fill()
    subIn.forward(5)
    subIn.right(90)
    subIn.forward(10)
    subIn.right(90)
    subIn.forward(5)
    subIn.right(90)
    subIn.forward(10)
    subIn.end_fill()

    #subLadder
    subIn.penup()
    subIn.setpos(-125,-25)
    subIn.pendown()
    subIn.width(3)
    subIn.forward(70)
    subIn.penup()
    subIn.setpos(-145, -25)
    subIn.pendown()
    subIn.forward(70)
    subIn.penup()
    subIn.setpos(-145, -20)
    subIn.pendown()
    subIn.right(90)
    subIn.forward(20)
    subIn.penup()
    subIn.setpos(-145, -10)
    subIn.pendown()
    subIn.forward(20)
    subIn.penup()
    subIn.setpos(-145, 0)
    subIn.pendown()
    subIn.forward(20)
    subIn.penup()
    subIn.setpos(-145, 10)
    subIn.pendown()
    subIn.forward(20)
    subIn.penup()
    subIn.setpos(-145, 20)
    subIn.pendown()
    subIn.forward(20)
    subIn.penup()
    subIn.setpos(-145, 30)
    subIn.pendown()
    subIn.forward(20)
    subIn.penup()
    subIn.setpos(-145, 40)
    subIn.pendown()
    subIn.forward(20)

    #subGate
    subIn.penup()
    subIn.width(0)
    subIn.setpos(-155,52)
    subIn.pendown()
    subIn.begin_fill()
    subIn.forward(40)
    subIn.left(90)
    subIn.forward(4)
    subIn.left(90)
    subIn.forward(17)
    subIn.right(90)
    subIn.forward(6)
    subIn.right(90)
    subIn.forward(11)
    subIn.left(90)
    subIn.forward(4)
    subIn.left(90)
    subIn.forward(28)
    subIn.left(90)
    subIn.forward(4)
    subIn.left(90)
    subIn.forward(11)
    subIn.right(90)
    subIn.forward(6)
    subIn.right(90)
    subIn.forward(17)
    subIn.left(90)
    subIn.forward(4)
    subIn.end_fill()

    #subPeriscope
    subIn.penup()
    subIn.setpos(20,25)
    subIn.width(7)
    subIn.pendown()
    subIn.right(180)
    subIn.forward(110)
    subIn.right(180)
    subIn.circle(15,-90)
    subIn.right(180)
    subIn.forward(15)


    subIn.hideturtle()

    


    

